language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0
      - python3.7-dev
      - python3-pip
      - python3-setuptools
      - ruby
      - libfl-dev
      - libmpfr-dev
      - libmpc-dev
      - clang

jobs:
  include:
    # - os: linux
    #   dist: bionic
    #   compiler: gcc
    #   env: PYTHON_EXECUTABLE=python3.7
    # - os: linux
    #   dist: bionic
    #   compiler: clang
    #   env: PYTHON_EXECUTABLE=python3.7
    - os: osx
      osx_image: xcode12
      # default python3 is python3.8 on mac
      env: PYTHON_EXECUTABLE=python3.8

script:
  - source ./scripts/travis-mac-install.sh
  # # brew sometimes fails on something even after a successful python installation
  # # we don't want the build to fail
  # - ./scripts/travis-setup-osx-python.sh || true
  # - sudo ${PYTHON_EXECUTABLE} -m pip install Cython==0.29 --install-option="--no-cython-compile"
  # - sudo ${PYTHON_EXECUTABLE} -m pip install pytest
  # - ./travis-scripts/setup-msat.sh --auto-yes
  # - ./contrib/setup-smt-switch.sh --with-msat --python --python-bin=$(which ${PYTHON_EXECUTABLE})
  # - sudo ${PYTHON_EXECUTABLE} -m pip install -e ./deps/smt-switch/build/python
  # - ./contrib/setup-btor2tools.sh
  # - ./contrib/setup-bison.sh
  # need to source for now so that coreir binary is in PATH for pycoreir
  - CXXFLAGS=-Wno-error=return-stack-address ./contrib/setup-coreir.sh
  # - export PATH=./deps/coreir/local/bin/:$PATH
  # - cd deps && git clone https://github.com/leonardt/pycoreir.git && cd pycoreir && sudo ${PYTHON_EXECUTABLE} -m pip install -e ./ && cd ../../
  # - ./configure.sh --with-msat --python --debug --with-coreir --python-bin=$(which ${PYTHON_EXECUTABLE})
  # - cd build && make -j2 && make test && cd ../
  # - sudo ${PYTHON_EXECUTABLE} -m pip install -e ./build/python
  # - ${PYTHON_EXECUTABLE} -m pytest ./tests
